version: '3.7'

services:
  main-api:
    build: ./.
    restart: always
    working_dir: /social_network
    command: gunicorn social_network.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/social_network/static
    environment:
      - HOST=http://localhost:8000
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=apidb
      - SQL_USER=apiuser
      - SQL_PASSWORD=apipassword
      - SQL_HOST=db
      - SQL_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=apidb
      - POSTGRES_USER=apiuser
      - POSTGRES_PASSWORD=apipassword

volumes:
  postgres_data:
  static_volume: